### ISSUE TITLE
 Feathers-configuration checks to see if a value is a part of the OS environment: 

### ISSUE THREAD

**Issue by Eckhardt-D** [CodingGarden/trello-clone#1]
The default.json of the server for the 'local' strategy: by setting the usernameField to 'username', feathers actually checks your OS (Windows) username instead of the input provided. Upon login this generates a 400 status code of Bad Request.

EDIT: The fix can be implemented by setting "usernameField": "\\\username"

**Comment by w3cj** [comment]
Nice catch! I'll test this out on my windows machine later today.

**Comment by w3cj** [comment]
🎉 ✨ 💚
